### ISSUE TITLE
Unable to launch https://<myurl>/api

### ISSUE THREAD

**Issue by TitiNantais** [r3dge/hellodoli#1]
Hello,

  When going to https://<myurl>/api i got the following error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.0".

  My configuration is Debian 10, NGinx, PHP 8.1.5 (cli)

Could you please help me ?

Thanks
Thierry

**Comment by r3dge** [comment]
The current version has been developped with PHP 7.4. We are going to upgrade the project to the 8.1 in the next version. I will come back to you in a couple of days. Or if you would feel free to PR.

**Comment by TitiNantais** [comment]
Thank you very much for your quick answer

**Comment by r3dge** [comment]
@TitiNantais 
Please give a try to v1.1.0. It has been upgraded to be compliant with php 8.1.
Before to run composer install, drop all folders inside /vendor.
Let me know.

**Comment by TitiNantais** [comment]
Unfortunatly I always have the same error and I get errors when launching composer install

![image](https://user-images.githubusercontent.com/105630106/169481361-e9145c32-e1ce-49b5-8de5-f2ea836b6532.png)

**Comment by r3dge** [comment]
Your mysql driver seems not installed on your server.
Please show the result of this command line : php -m | grep mysql

**Comment by TitiNantais** [comment]
Here it is

root@vps718156:/var/www/hellodoli-main# php -m | grep mysql
mysqli
mysqlnd
pdo_mysql

**Comment by r3dge** [comment]
the driver is installed. Now check if the driver is enabled. In your php.ini find : extension=pdo_mysql.so
If there is a ";" at the beginning of the line, remove it and the restart apache.
Can you show your .env file ?

**Comment by r3dge** [comment]
@TitiNantais did you fix this issue on your environment ?

**Comment by TitiNantais** [comment]
No sorry, always have the same pb
