### ISSUE TITLE
No transactions

### ISSUE THREAD

**Issue by TitiNantais** [r3dge/hellodoli#2]
Good morning

  Everything seems to be configured correctly but the transactions generated in HelloAsso do not go back to Dolibarr. How is it possible to check where it is blocking?

**Comment by r3dge** [comment]
Hi,
You should check the database. If records are not consumed in the "notifications" table it means your worker is not started.
In this case check the setup of your cron task.
You could run it manually : bin/console messenger:consume async -vv

**Comment by TitiNantais** [comment]
I've just launched the worker manually, done an adhesion on HelloAsso site, and I get nothing in the DB ...

**Comment by r3dge** [comment]
when a notification is received from HelloAsso, a record is added in the database. When the worker is started it consumes this notification and remove the record after processing. If you have nothing in the db it means that hellodoli is not receiving notifications from HelloAsso. 

First you should check if the callback URL is correct in HelloAsso. It should be like that : https://<YOUR_DOMAIN>/api/notifications

Second check if the URL is working : https://<YOUR_DOMAIN>/api/notifications
Try to send a post query to check if the record is correctly created in the database.

**Comment by TitiNantais** [comment]
I've tried to manualy test the api and I get an error 500:

{
  "@context": "/api/contexts/Error",
  "@type": "hydra:Error",
  "hydra:title": "An error occurred",
  "hydra:description": "Internal Server Error"
}

My dbb definition in .env is

DATABASE_URL="mysql://<****>:<***>@127.0.0.1:3306/ANS-HELLODOLI?serverVersion=mysql-8.0.27"

**Comment by r3dge** [comment]
Could you give the error details in the log ? (var/log)

**Comment by TitiNantais** [comment]
Invalid platform version "mysql-8.0.27

**Comment by r3dge** [comment]
Give a try to that config in your .env and let me know :  

DATABASE_URL="mysql://<*>:<>@127.0.0.1:3306/ANS-HELLODOLI?serverVersion=8.0.27"

**Comment by TitiNantais** [comment]
it's better with this parameter but now I get

2023/03/24 04:56:51 [error] 9341#9341: *3855 FastCGI sent in stderr: "PHP message: [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "" at /var/www/hellodoli-main/src/Controller/HelloAssoController.php line 22" while reading response header from upstream, client: 51.15.195.246, server: hellodoli.activnantes.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "hellodoli.activnantessupports.com"

**Comment by r3dge** [comment]
It seems you are using the wrong url. This error occur because you are using "/" instead of "/api/notifications
